name: Upload Python Package

on:
  push:
    branches:
      - main

jobs:
  update:
    name: Test and publish monpetitsalon package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Hello world
        run: echo "Hello world !"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip pytest
      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install poetry pytest
      #     poetry install
      - name: Run tests
        run: poetry run pytest
      # - name: Build and publish package
      #   run: |
      #     poetry config repositories.test-pypi https://test.pypi.org/legacy/
      #     poetry config pypi-token.test-pypi ${{ secrets.MONPETITSALON_SRC_TOKEN }}
      #     poetry publish --build -r test-pypi
